#!/usr/bin/python3

import argparse
import re, glob
from subprocess import call, check_output
from datetime import datetime

def _replacefile(file, match, replace, dryrun=False):
    if dryrun:
        print(f"{file}: {match} -> {replace}")
        return
    with open(file, encoding="utf-8") as inf:
        lines = [re.sub(match, replace, l) for l in inf.readlines()]
    with open(file, "w", encoding="utf-8") as outf:
        for l in lines:
            outf.write(l)

def _git(cmd, *a, dryrun=False):
    s = ["git", cmd]+list(a)
    if dryrun:
        print(" ".join(s))
    else:
        call(s)

def _dch(version, dryrun=False):
    tz = datetime.now().astimezone().tzinfo
    dt = datetime.now(tz)
    date = dt.strftime("%a, %d %b %Y %H:%M:%S %z")
    txt = """ptxprint ({0}-1ubuntu1) jammy; urgency=medium

  * Bumped release to {0}

 -- Martin Hosken <martin_hosken@sil.org>  {1}

""".format(version, date)
    if dryrun:
        print(txt)
        return
    with open("debian/changelog") as inf:
        lines = list(inf.readlines())
    with open("debian/changelog", "w") as outf:
        outf.write(txt)
        for l in lines:
            outf.write(l)

def get_branches():
    txt = check_output(["git", "branch", "-vv"])
    res = {}
    for l in txt.decode("utf-8").split("\n"):
        m = re.match(r"^  (\S+)\s.*?\[(.*?)\]", l)
        if m:
            name = m.group(1)
            if ':' in m.group(2):
                upstream = m.group(2)[:m.group(2).find(':')]
            else:
                upstream = m.group(2)
            res[name] = upstream
    return res

#def get_gitver():
#    txt = check_output(["git", "describe", "--long"]).decode("utf-8", errors="ignore")
#    return txt.strip()

parser = argparse.ArgumentParser()
parser.add_argument("version")
parser.add_argument("-a", action="store_true")
parser.add_argument("-s", action="store_true", help="tag with -s")
parser.add_argument("-n","--noaction",action="store_true", default=False, help="dry run")
args = parser.parse_args()
tagopt = "-a"
if args.s:
    tagopt = "-s"

def replacefile(*a, **kw):
    _replacefile(*a, dryrun=args.noaction, **kw)
def git(*a, **kw):
    _git(*a, dryrun=args.noaction, **kw)
def dch(*a, **kw):
    _dch(*a, dryrun=args.noaction, **kw)
def syscmd(*a, **kw):
    print(" ".join(a))
    if not args.noaction:
        call(a, **kw)


# gitversion = get_gitver()
replacefile("pyproject.toml", r'(version = ").*?"', r'\g<1>'+args.version+'"')
replacefile("src/usfmtc/__init__.py", r'(version = ").*?"', r'\g<1>'+args.version+'"')

branches = get_branches()

git("commit", "-a", "-m", "Releasing "+args.version)
git("tag", tagopt, "-m", "Tagging "+args.version, args.version)
git("push", "--tag")
git("push")

syscmd("python3", "-m", "build")
pypyfiles = glob.glob("dist/*-"+args.version+"*")
syscmd("twine", "upload", *pypyfiles)
